### ISSUE TITLE
FZF 設定を vim に追加

### ISSUE THREAD

**Issue by hanamogura** [hanamogura/vim#1]
## TODO
- [] vim-plugin の追加 
- [] Requerements 追加 (vim-plugin)
- [] fzf, fzf-vim プラグインの追加
